#!/usr/bin/env python3
"""
merge_srt.py — merge chunk (part) SRT files into the final movie script.

Usage:
  python3 merge_srt.py part1.srt part2.srt part3.srt --out "Movie Name.srt"
  python3 merge_srt.py .work/parts/*.srt --out "Movie Name.srt" --bom

Each part was generated by make_srt.py from its chunk manifest, so its
timestamps are ALREADY absolute (whole-film time). Merging therefore only
has to concatenate in order and renumber the entries; this script also
sanity-checks that the timeline is continuous:

  - parts are ordered by their first entry's start time (order given on the
    command line is used; out-of-order input triggers a warning)
  - gaps/overlaps between consecutive entries are reported
  - the final file gets a fresh 1..N numbering

Pass the parts in chronological order (part1, part2, ...).
"""

import argparse
import glob
import re
import sys
from pathlib import Path

TS_RE = re.compile(
    r"^(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*"
    r"(\d{2}):(\d{2}):(\d{2}),(\d{3})$")


def parse_srt(path: Path) -> list:
    """Returns [(start_s, end_s, text), ...] for one .srt file."""
    raw = path.read_text(encoding="utf-8-sig")  # tolerate BOM
    entries = []
    for block in re.split(r"\n\s*\n", raw.strip()):
        lines = [ln for ln in block.splitlines() if ln.strip()]
        if len(lines) < 2:
            continue
        m = TS_RE.match(lines[1].strip())
        if not m:
            print(f"WARNING: {path.name}: skipping malformed block:\n"
                  f"  {lines[1][:80]}", file=sys.stderr)
            continue
        g = list(map(int, m.groups()))
        start = g[0] * 3600 + g[1] * 60 + g[2] + g[3] / 1000
        end = g[4] * 3600 + g[5] * 60 + g[6] + g[7] / 1000
        text = " ".join(" ".join(lines[2:]).split())
        entries.append((start, end, text))
    if not entries:
        raise RuntimeError(f"no valid entries found in {path}")
    return entries


def ts(t: float) -> str:
    ms = max(0, int(round(t * 1000)))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1_000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("parts", nargs="+",
                    help="part .srt files in chronological order "
                         "(glob ok: .work/parts/*.srt)")
    ap.add_argument("--out", required=True,
                    help='final .srt path (e.g. "Movie Name.srt")')
    ap.add_argument("--bom", action="store_true",
                    help="write a UTF-8 BOM (helps some players with CJK etc.)")
    args = ap.parse_args()

    paths = []
    for p in args.parts:
        if Path(p).is_file():
            paths.append(Path(p))
        else:
            paths.extend(sorted(Path(x) for x in glob.glob(p)
                                if Path(x).is_file()))
    if not paths:
        print("ERROR: no part files matched", file=sys.stderr)
        return 1

    all_entries = []
    prev_end = None
    first_starts = []
    for path in paths:
        entries = parse_srt(path)
        first_starts.append(entries[0][0])
        for start, end, text in entries:
            if prev_end is not None:
                gap = start - prev_end
                if gap > 1.0:
                    print(f"NOTE: {gap:.1f}s gap before {path.name} "
                          f"({ts(prev_end)} -> {ts(start)})", file=sys.stderr)
                elif gap < -0.5:
                    print(f"NOTE: {abs(gap):.1f}s overlap before {path.name} "
                          f"({ts(prev_end)} -> {ts(start)})", file=sys.stderr)
            prev_end = end
        all_entries.extend(entries)
        print(f"  {path.name}: {len(entries)} entries "
              f"({ts(entries[0][0])} - {ts(entries[-1][1])})")

    if first_starts != sorted(first_starts):
        print("WARNING: parts were not in chronological order — "
              "entries merged as given; check the result", file=sys.stderr)

    data = "".join(
        f"{i}\n{ts(start)} --> {ts(end)}\n{text}\n\n"
        for i, (start, end, text) in enumerate(all_entries, 1))
    if args.bom:
        data = "\ufeff" + data
    out = Path(args.out).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(data, encoding="utf-8")
    print(f"\nwrote {out} — {len(all_entries)} entries from "
          f"{len(paths)} part(s), {ts(all_entries[0][0])} to "
          f"{ts(all_entries[-1][1])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
